### ISSUE TITLE
Use `LP_TITLE_OPEN=$'\E]2'` for tmux 

### ISSUE THREAD

**Issue by kmARC** [liquidprompt/liquidprompt#716]
The OSC sequence for setting tmux pane title is `\E]2` (see https://linux.die.net/man/1/tmux)

Currently liquidprompt sets this as `\Ek` (see [liquidprompt#L613](https://github.com/nojhan/liquidprompt/blob/6f0dc9f7dda99fe98c6dce26be5e461692782c6d/liquidprompt))

Shell: `5.1.16(1)-release`

Operating system: `Darwin Laptop056 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64 arm Darwin`

Liquidprompt version: `/opt/homebrew/Cellar/liquidprompt/2.1.2 `

### Expected Behavior
Liquidprompt sets tmux pane titles

### Current Behavior
It doesn't

### Possible Solution
Changing [liquidprompt#L613](https://github.com/nojhan/liquidprompt/blob/6f0dc9f7dda99fe98c6dce26be5e461692782c6d/liquidprompt) to 
```sh
        LP_TITLE_OPEN=$'\E]2'
```
fixes the issue

**Comment by Rycieos** [comment]
Thanks for the report, documentation, and suggested solution.

Despite what the docs suggest, I am not able to reproduce this.

I need to have `set -g allow-rename on` in my Tmux config, but then the window title is set correctly with no changes to Liquidprompt. I always assumed Tmux had compatibility with Screen.

Changing `LP_TITLE_OPEN` to `$'\E]2'` as you suggest, or `$'\E]2;'` as I think the docs actually meant both make the window title not change.

Maybe you have a different configuration in your Tmux config? Or a different Tmux version? I tested on Tmux 2.7 and 3.3a.

**Comment by kmARC** [comment]
Ohh... So I thought this supposedly renames the titles of the **tmux panes** not the **tmux windows**. 

Example with  `LP_TITLE_OPEN=$'\Ek'`:
<img width="1239" alt="Screenshot 2022-07-01 at 09 07 14" src="https://user-images.githubusercontent.com/6640417/176843404-e3b6f96d-5fe2-4c0e-baba-6fac26f163a5.png">

Example with  `LP_TITLE_OPEN=$'\E]2'` (no `;` at the end):
<img width="1239" alt="Screenshot 2022-07-01 at 09 08 04" src="https://user-images.githubusercontent.com/6640417/176843497-e60f12df-a584-438e-b845-acf2b830385d.png">

Actually I rather want to keep the windows' names to be automatically set just to be the command name that the currently focused pane runs, or manually (which is the default I believe). 

So then this might be an extra functionality which can be implemented in liquidprompt?

**Comment by Rycieos** [comment]
Ah I see. Hm, that shouldn't be too hard to implement. Make an option like `LP_TMUX_TITLE_PANE` that would set `LP_TITLE_OPEN=$'\E]2'` if Tmux was detected. Is that what you are thinking?

**Comment by Rycieos** [comment]
Sorry for the delay; I finally added this.

**Comment by kmARC** [comment]
Better late than never! Thank you :-)
