### ISSUE TITLE
Generic hook

### ISSUE THREAD

**Issue by nojhan** [liquidprompt/liquidprompt#721]
Provide a generic hook that may be used by a (power) user to call configuration change/functions whenever the prompt is called.

For example: change the locale configuration whenever entering a Git directory, read a `.env` file when entering a directory, send notifications, etc.

### Description

The hook takes the form of a normalized function name that may be overloaded in the RC file, and which is called automatically by the prompt if `LP_HOOK` is set.
The hook would be located somewhere near the end of the prompt, to allow its user to display stuff with it.

### How will this be useful?

- change the locale configuration whenever entering some directory,
- more generally, change the environment config when entering a directory or whatever virtual env/container,
- send notifications to the system if such or such threshold is overcome,
- change Liquidprompt’s theme for some directories,
- test simple features before suggesting a PR to LP :-)

**Comment by nojhan** [comment]
Probably more a job for [direnv](https://direnv.net/) than for the prompt.

**Comment by Rycieos** [comment]
> Probably more a job for [direnv](https://direnv.net/) or [autoenv](https://github.com/hyperupcall/autoenv) than for the prompt.

I agree. I have used direnv before, and it is quite slick, and already solves the "configuration per directory" problem better than Liquidprompt ever could.

That doesn't solve all your suggestions though, and I have contemplated hooks like this for a while, so I'll leave this open and see if we can get any specific use cases laid out.

**Comment by nojhan** [comment]
FTR, I tried with direnv, but it seems the way it handles shell makes it impossible to switch LP themes, for instance.

**Comment by Rycieos** [comment]
Ah, that makes sense. Maybe we could add a config variable that sets the theme? So if you set `LP_THEME` or something, at the next prompt LP picks up on that and switches theme for you?

**Comment by nojhan** [comment]
If that's a working workaround for using it with direnv, I think that would be a great addition.
