### ISSUE TITLE
View the remote as well as the branch when using git

### ISSUE THREAD

**Issue by maxulysse** [liquidprompt/liquidprompt#782]
### Description

I would love to be able to see the remote as well as the branch when developing with git.

### How will this be useful?

I pushed to the wrong master, and that could probably have been avoided if I checked on which remote I was beforehand.
Knowing that already in my prompt, would be amazing

### Example prompt

This is what I have

```bash
· > symbol ± > BRANCH >  ✝ > 
```

I would like:

```bash
· > symbol ± > REMOTE > BRANCH >  ✝ > 
```

Just knowing if `origin` or `upstream` would be tip top.

**Comment by Rycieos** [comment]
Git doesn't have a concept of "current" or default remote, at least not repo wide. It does have that concept per branch, which can be set with `git branch --set-upstream-to` or `git push --set-upstream`. Is that the information you would want?

**Comment by nojhan** [comment]
That would be feasible by parsing `.git/config`, thus being quite fast. Albeit this is a config file, and thus may need associative tables to be a clean code.
