### ISSUE TITLE
Memory display on Darwin is inaccurate

### ISSUE THREAD

**Issue by tomhoover** [liquidprompt/liquidprompt#787]
With the most recent update to liquidprompt, the following was added to my prompt:
```
⏚ M0% [:~] %
```
Not recognizing `M0%`, I changed `LP_DISPLAY_VALUES_AS_PERCENTS` back to the default of `0`, and it then displayed:
```
⏚ M85.20GiB [:~] %
```
With a number that high, I initially assumed that it was indicating free disk space, but I currently have over 100GB free. After a searching around a bit more, I realized it was supposed to be a memory display (https://github.com/nojhan/liquidprompt/pull/770). 

The issue is that my Macbook Pro only has 16GB of memory. 

Shell: zsh 5.9

Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

Liquid Prompt version: 9a6cff9981323b15bfcdbc7d49720441ea97ce0a

### Steps to Reproduce

1. Macbook Pro (M1), running Ventura 13.5.1
2. Use default liquidprompt confiig
3. No other steps required

### Expected Behavior

Accurate display of memory
### Current Behavior

Inaccurate display of memory
### Possible Solution

No suggestions, but I can hide it by changing the default of `LP_ENABLE_RAM=1` to `LP_ENABLE_RAM=0`. 😄

**Comment by Rycieos** [comment]
I can replicate this, at least somewhat. My Mac has 64GB of memory, but my prompt is showing:
```
M20.65TiB
```
Of course I had to turn the thresholds way up to see that, which is why I never noticed.

This is actually a number of very small mistakes that canceled each other out on Linux, but don't on MacOS. I'll want to get @nojhan's eyes on my PR before I push a fix.

**Comment by nojhan** [comment]
I am testing on MacOS Ventura 13.2.1 and it seems that the RAM estimate is indeed different than the one estimated with the Activity Monitor. However, PR #788, while fixing one order of magnitude, does not seem to solve the issue of the discrepancy with the AM.

**Comment by nojhan** [comment]
PR #788 may have finished fixing the problem on MacOS, please test :smile:
