### ISSUE TITLE
-bash: 100 * lp_ram_avail_bytes / lp_ram_total_bytes : division by 0 (error token is "lp_ram_total_bytes ")

### ISSUE THREAD

**Issue by rm1984** [liquidprompt/liquidprompt#789]
Currently running FreeBSD 13.2-RELEASE-p1 FreeBSD 13.2-RELEASE-p1 GENERIC amd64.
I get that error/warning at every command I type.

Shell: **Bash 5.2.15(0)-release**

Operating system: **FreeBSD 13.2-RELEASE-p1 FreeBSD 13.2-RELEASE-p1 GENERIC amd64**

Liquid Prompt version: **9a6cff9981323b15bfcdbc7d49720441ea97ce0a**

### Expected Behavior
No errors.

### Current Behavior
As long as I type commands, I always get the following message:
`-bash: 100 * lp_ram_avail_bytes / lp_ram_total_bytes : division by 0 (error token is "lp_ram_total_bytes ")`

**Comment by Rycieos** [comment]
This is probably a bug in how we read the `/var/run/dmesg.boot` file. Can you upload the contents of that file? Alternatively, you can use [external-tool-tester.sh](https://github.com/liquidprompt/liquidprompt/blob/master/tools/external-tool-tester.sh) script which will do it for you.

**Comment by rm1984** [comment]
Sure, here you can find my `/var/run/dmesg.boot` file:

[dmesg.boot.txt](https://github.com/liquidprompt/liquidprompt/files/12669970/dmesg.boot.txt)

I take this opportunity to point out that the `external-tool-tester.sh` script doesn't seem to support FreeBSD.

Thanks!

**Comment by rm1984** [comment]
Hi, this is the error I get:

```
$ ./external-tool-tester.sh 
./external-tool-tester.sh: shopt: not found
This script must be redirected to a file, or special characters will be lost
  Ex: ./external-tool-tester.sh > output.txt
Or, to upload directly:
  ./external-tool-tester.sh | curl -F "sprunge=<-" "http://sprunge.us"
```

I'm currently running **FreeBSD 13.2-RELEASE-p1** with **bash-5.2.15**.
I confirm that the `shopt` built-in command works correctly.

**Comment by Rycieos** [comment]
Ah, that's my mistake. I always run it with `bash ./external-tool-tester.sh` by habit. I fixed it to make it compatible with any POSIX shell (hopefully) just now with 09fc9ecbcbaf7ed61ba64f87123f487c8e41a584.

The other error lines are expected.
