### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by hoclun-rigsep** [liquidprompt/liquidprompt#793]
Last tagged release was 150 commits and 27 months ago; I discovered this while trying to use the dotmatrix theme. Perhaps it is time?

**Comment by Rycieos** [comment]
I agree; I was thinking the same thing last week.

There are a few issues still left in the [2.2 milestone](https://github.com/liquidprompt/liquidprompt/milestone/8), but most have sat without input or any design work for a while, so I will probably ship 2.2 without them. There is still one issue that I want to resolve quickly, and I want to do another pass on open issues and PRs before cutting an RC. Then I just need to write the Changelog.

**Comment by Rycieos** [comment]
I have released [v2.2.0-rc.1](https://github.com/liquidprompt/liquidprompt/releases/tag/v2.2.0-rc.1). I will release v2.2.0 when I'm confident it's stable.
