### ISSUE TITLE
Missing LP_ENABLE_* configuration variables

### ISSUE THREAD

**Issue by nojhan** [liquidprompt/liquidprompt#796]
Some configuration variable enabling some features are missing.

### Description

- `LP_ENABLE_DISPLAY`, use in `_lp_connected_display`,
- `LP_ENABLE_CHROOT`, use in `_lp_chroot`,
- `LP_ENABLE_MUX`, use in `_lp_multiplexer`

### How will this be useful?

I would have needed them for the [Solid](https://github.com/nojhan/lp-solid) theme,
which displays if a data source is enabled or not, before displaying its value.

**Comment by Rycieos** [comment]
I agree, there is no good argument for not having a way to disable features.

However, a theme should never be checking `LP_ENABLE_*` directly. The data function should check it, and the theme just calls the data function, and aborts if the error code is set.

**Comment by nojhan** [comment]
Fixed in #801 via 6cb4900.
