### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by DamienCassou** [liquidprompt/liquidprompt#808]
The last release is from June last year. Is it time to make a new one?

**Comment by Rycieos** [comment]
Somewhat a duplicate of #793, though maybe I closed that one too early since v2.2.0 isn't quite out yet. I released v2.2.0-rc.1 a month ago, and just released [v2.2.0-rc.2](https://github.com/liquidprompt/liquidprompt/releases/tag/v2.2.0-rc.2) just now.

**Comment by Rycieos** [comment]
[v2.2.0](https://github.com/liquidprompt/liquidprompt/releases/tag/v2.2.0) was just released.
