### ISSUE TITLE
Update screenshots in the doc

### ISSUE THREAD

**Issue by nojhan** [liquidprompt/liquidprompt#810]
Screenshots in the documentation should be updated to reflect improvement from v2.2.

In the "Why Liquid Prompt?" section: use normalized screenshots for at least:

- [x] default theme
- [x] unfold
- [x] 256-colors presets
- [x] unicode presets

Questions: should we show some extern themes there?

**Comment by Rycieos** [comment]
> Questions: should we show some extern themes there?

I think themes in the liquidprompt org should have links to their documentation. Other themes should be on the wiki page, which can be linked in the docs.

**Comment by Rycieos** [comment]
I'm closing this as it seems like all the goals were accomplished here.
