### ISSUE TITLE
Ability to customize title separately from PS1

### ISSUE THREAD

**Issue by joshuaspence** [liquidprompt/liquidprompt#820]
### Description

I want to use the default `$PS1` generated by liquidprompt but I want to customize the title to be much simpler. Specifically I only want the title to contain `$LP_PWD`. I am able to achieve this today by writing a custom theme, but I have to copy-paste `$LP_PS1` from liquidprompt and presumably then also keep it up to date across version upgrades. Ideally I could customize `$PS1` and title separately.

### How will this be useful?

When I have multiple terminal tabs open this will allow me to easily distinguish them.

### Example prompt

If I set `LP_ENABLE_TITLE=1` and `LP_ENABLE_TITLE_COMMAND=1` then my title looks something like `[jspence:~/.local/share/chezmoi]± sleep 60`. I'd rather this be shorter, such as `~/.local/share/chezmoi sleep 60`.

**Comment by joshuaspence** [comment]
Ok that was a lot easier than what I was doing. Apologies, I should've read the theme documentation more. I was looking at the config docs mostly.

**Comment by Rycieos** [comment]
Don't apologize; it's quite likely the docs on that part could use improving. Let me know if there are any parts that are confusing and could be improved.
