### ISSUE TITLE
liquidprompt git modification state not shown under a git worktree folder

### ISSUE THREAD

**Issue by samuelortion** [liquidprompt/liquidprompt#833]
When I am under a folder of a [git worktree](https://git-scm.com/docs/git-worktree), the liquidprompt theme [jolly](https://github.com/nojhan/lp-jolly) does not show the useful indication on git repository modification state.

Shell: zsh 5.9

Operating system: Linux 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

Liquid Prompt version: git commit: 2676c18d00b42611db23ac77d97c3f15731b84c3
Jolly version: git commit: 3aaf5fa592705e1576432fb2544812155da3d19c

### Steps to Reproduce

1. Create a git worktree in a subfolder:
  ```console
   $ git worktree add branches/test test # Add a worktree for test in branches/test
   ```
2. Move to the woktree folder and make some edit
  ```console
   $ cd branches/test # and make some edit.
  ```
### Expected Behavior

It would be great if the modification status of the branch set in the worktree was shown in the prompt.

### Current Behavior

Jolly theme displays `✝╱? `, showing It detected it is in a git repository, but does not show the modification state.

**Comment by nojhan** [comment]
Can you issue the command `lp_theme default` and check whether this happens with the default theme as well?

**Comment by samuelortion** [comment]
It seems to appear with `lp_theme default` too.
Here is what I get on the prompt within a worktree subfolder:
```text
(+1/-1)+* ±
```
It does not change even If I make some edit, apparently, such as creating a brand-new file, or editing a previously committed one, for instance.

**Comment by Rycieos** [comment]
I can't reproduce this with either the `default` or `jolly` themes, neither with Bash 5.1:

```
[mark@jaguar:~/dev/liquidprompt] master+ ± git worktree add branches/test pr/815
Preparing worktree (checking out 'pr/815')
HEAD is now at cb86f56 Added tests for rvm, with my newly acquired knowledge from the Perl implementation
[mark@jaguar:~/dev/liquidprompt] master+* ± cd branches/test/
[mark@jaguar:~/dev/liquidprompt/branches/test] pr/815+ ± vim README.md
[mark@jaguar:~/dev/liquidprompt/branches/test] pr/815(+0/-4)+ ± lp_theme jolly

T ▙ ▚ ▜█mark ▛ jaguar ▛ ~ ╱ dev ╱ liquidprompt ╱ branches ╱ test ▛                                                                                      ▖ ▘▞▟
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
· ▛ ± ▛ pr/815 ▙ ▜█+0╱-4 ▛ ✝ ▛ ⯀
```

Nor with Zsh-5.9:
```
[mark@jaguar:~/dev/liquidprompt]└2 master+* ± cd branches/test
[mark@jaguar:~/dev/liquidprompt/branches/test]└2 pr/815(+0/-4)+ ± lp_theme jolly

T ▙ ▚ ▜█mark ▛ jaguar ▛ ~ ╱ dev ╱ liquidprompt ╱ branches ╱ test ▛                                                                                      ▖ ▘▞▟
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
· ▛ ± ▛ pr/815 ▙ ▜█+0╱-4 ▛ ✝ ▛ ⯀⯀
```

Could you try with a fresh worktree, and see if that changes anything? I have been using Git worktrees daily for months, and have not seen this issue.

**Comment by samuelortion** [comment]
Indeed, it does work on a fresh git repository and git worktree in it.
I should have tested this before, sorry.
I don't know what is special with my other repository.

**Comment by Rycieos** [comment]
Try running `git diff --shortstat` in your broken worktree to see what it prints. That is what `liquidprompt` uses internally to get the data for that section.

Assuming it returns something like
> 1 file changed, 1 insertion(+), 1 deletion(-)

as your output would suggest, run `git diff` and try to track down how Git is seeing things different than you expect.
