### ISSUE TITLE
Override the string when perlbrew detect that you use system's perl version

### ISSUE THREAD

**Issue by tkapias** [liquidprompt/liquidprompt#834]
Shell: bash 5.2.21(1)-release
Operating system: Linux 6.7.12-amd64 Debian GNU/Linux trixie/sid GNU/Linux
Liquid Prompt version: da2aebc7e9635c54763b046a08f7231be5b7d980

1. Install perlbrew, but leave the system perl version active
2. Install liquidprompt with the default LP_ENABLE_PERL_VENV=1
3. open a new shell.

### Current Behavior

Liquidprompt will display "Currently using system perl".
Because it is what perlbrew output with `perlbrew use`.

### Possible Solution

Override the default string with the system version from perl itself:

``` patch
--- liquidprompt        2024-05-25 17:10:23.947286677 +0700
+++ /home/tomasz/.bashrc.d/21-prompt-liquidprompt.bashrc        2024-05-25 17:09:04.628564857 +0700
@@ -2063,7 +2063,9 @@                                                        
                                                                             
     if [[ "$_LP_PERL_VENV_PROGRAM" = "perlbrew" ]] ; then
         local perlbrew_perl_ver="$(perlbrew use)"       
-                                                                            
+        if [[ "$perlbrew_perl_ver" = "Currently using system perl" ]] ; then 
+            local perlbrew_perl_ver="$(perl -v | sed -nE 's/.*\((v.+)\).*/\1/p')(system)"
+        fi          
         # Example: Currently using perl-5.38.0                                                                                                           
         __lp_escape "${perlbrew_perl_ver##*perl-}"
         lp_perl_env=$ret
```

**Comment by tkapias** [comment]
My patch would display `|v5.38.2(system)|`, when perlbrew is activated to use another version it displays `|5.38.2|`.

I see that for NVM, it displays `|v18.18.2|`.

Maybe it would be nice to refactor all those commands and parse them to always display the same template? Something like :

- app-version(system)
- perl-5.38.2
- perl-5.38.2(system)
- node-18.18.2
- ...

**Comment by tkapias** [comment]
I started writing the changes for Node and Ruby and eventually changed my mind.

The releases of these tools are likely to evolve, and the basic design was probably not to display the system versions.

So it would probably be best not to display anything when perlbrew indicates the system version.

``` diff
--- Builds/liquidprompt/liquidprompt    2024-05-25 17:10:23.947286677 +0700
+++ /home/tomasz/.bashrc.d/21-liquidprompt.bashrc       2024-05-27 22:44:09.627619213 +0700
@@ -2063,7 +2063,9 @@
 
     if [[ "$_LP_PERL_VENV_PROGRAM" = "perlbrew" ]] ; then
         local perlbrew_perl_ver="$(perlbrew use)"
-
+        if [[ "$perlbrew_perl_ver" = "Currently using system perl" ]] ; then
+            return 1
+        fi
         # Example: Currently using perl-5.38.0
         __lp_escape "${perlbrew_perl_ver##*perl-}"
         lp_perl_env=$ret
```

**Comment by Rycieos** [comment]
I think your patch is probably a good idea. The magic string isn't great, but it ripped directly from the source where it is a magic string:
https://github.com/gugod/App-perlbrew/blob/dd5a3191fedbf90b04cb61acb63ab5d59833e2cd/perlbrew#L3561

I took the liberty of applying the same logic to our treatment of `plenv`, `rbenv`, and `rvm-prompt`. All other development environments besides these 4 work that way already, and our docs even suggest that they would do nothing if no env was detected.

Thanks for the report and the suggestion!
