### ISSUE TITLE
PR #827 Breaks `LP_ENABLE_ERROR=1` for all exit status codes, not just 130

### ISSUE THREAD

**Issue by rpatterson** [liquidprompt/liquidprompt#836]
After updating to `v2.2.0`, I discovered that commands that exit with non-zero status were not being reported in the subsequent prompt. It has the same behavior if I checkout [the commit that merged this PR](https://github.com/nojhan/liquidprompt/commit/1b87fbd0922c5938baa5ee2ff3c92361560b19dc). If I checkout [the commit immediately preceding the merge](https://github.com/liquidprompt/liquidprompt/commit/af0a69ac260ae3278e9b449acb5c4ebf7e5bfef4) of PR #827, it works as it did before, reporting both 130 and all other non-zero exit status codes.

LMK if you prefer I report this as a separate issue and I'll copy this over. Here are my technical details:

```
$ echo $BASH_VERSION
5.1.16(1)-release
$ uname -a
Linux ... 6.8.0-76060800daily20240311-generic #202403110203~1715181801~22.04~aba43ee SMP PREEMPT_DYNAMIC Wed M x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Pop
Description:    Pop!_OS 22.04 LTS
Release:        22.04
Codename:       jammy
$ git rev-parse HEAD
1b87fbd0922c5938baa5ee2ff3c92361560b19dc
```

**Comment by Rycieos** [comment]
I cannot reproduce this:
```
[mark@jaguar:~/dev/liquidprompt] master ± LP_HIDE_EMPTY_ERROR=0
[mark@jaguar:~/dev/liquidprompt] master ± ^C
[mark@jaguar:~/dev/liquidprompt] master 130 ±
[mark@jaguar:~/dev/liquidprompt] master 130 ±
[mark@jaguar:~/dev/liquidprompt] master 130 ± LP_HIDE_EMPTY_ERROR=1
[mark@jaguar:~/dev/liquidprompt] master ± ^C
[mark@jaguar:~/dev/liquidprompt] master ± false
[mark@jaguar:~/dev/liquidprompt] master 1 ± ^C
[mark@jaguar:~/dev/liquidprompt] master ± false
[mark@jaguar:~/dev/liquidprompt] master 1 ±
[mark@jaguar:~/dev/liquidprompt] master ±
```

Please run the `tools/external-tool-tester.sh` script and attach the output, post the output of `declare -p | grep ' LP_'`, and include reproduction steps.

**Comment by rpatterson** [comment]
> Please run...

```
2d [:/srv/checkouts/ubuntu/usr/local/src/liquidprompt]
± ./tools/external-tool-tester.sh
This script must be redirected to a file, or special characters will be lost
  Ex: ./tools/external-tool-tester.sh > output.txt
Or, to upload directly:
  ./tools/external-tool-tester.sh | curl -F "sprunge=<-" "http://sprunge.us"
2d [:/srv/checkouts/ubuntu/usr/local/src/liquidprompt]
± ./tools/external-tool-tester.sh | curl -F "sprunge=<-" "http://sprunge.us"
Tests complete.
Make sure to upload the file directly, do not `cat` and copy paste!

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 Page not found</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Page not found</h1>
<h2>The requested URL was not found on this server.</h2>
<h2></h2>
</body></html>
2d [:/srv/checkouts/ubuntu/usr/local/src/liquidprompt]
± declare -p | grep ' LP_' >/tmp/liquidprompt-issues-836-declare.log
```

Contents of `/tmp/liquidprompt-issues-836-declare.log`:

```
declare -- LP_ALWAYS_DISPLAY_VALUES="1"
declare -- LP_AWS_PROFILE=""
declare -- LP_BATT=""
declare -- LP_BATTERY_THRESHOLD="75"
declare -- LP_BRACKET_CLOSE="\\[[1m[34m\\]]\\[(B[m\\]"
declare -- LP_BRACKET_OPEN="\\[[1m[34m\\][\\[(B[m\\]"
declare -- LP_CMAKE=""
declare -a LP_COLORMAP=([0]="" [1]=$'\\[\E[32m\\]' [2]=$'\\[\E[1m\E[32m\\]' [3]=$'\\[\E[33m\\]' [4]=$'\\[\E[1m\E[33m\\]' [5]=$'\\[\E[31m\\]' [6]=$'\\[\E[1m\E[31m\\]' [7]=$'\\[\E[30m\E[41m\\]' [8]=$'\\[\E[1m\E[37m\E[41m\\]' [9]=$'\\[\E[1m\E[33m\E[41m\\]')
declare -- LP_COLOR_AWS_PROFILE="\\[[33m\\]"
declare -- LP_COLOR_CHANGES="\\[[31m\\]"
declare -- LP_COLOR_CHARGING_ABOVE="\\[[32m\\]"
declare -- LP_COLOR_CHARGING_UNDER="\\[[33m\\]"
declare -- LP_COLOR_CMAKE_DEBUG="\\[[35m\\]"
declare -- LP_COLOR_CMAKE_RELEASE="\\[[36m\\]"
declare -- LP_COLOR_CMAKE_RWDI="\\[[34m\\]"
declare -- LP_COLOR_COMMITS="\\[[33m\\]"
declare -- LP_COLOR_COMMITS_BEHIND="\\[[1m[31m\\]"
declare -- LP_COLOR_CONTAINER="\\[[1m[34m\\]"
declare -- LP_COLOR_DIFF="\\[[35m\\]"
declare -- LP_COLOR_DIRSTACK="\\[[1m[33m\\]"
declare -- LP_COLOR_DISCHARGING_ABOVE="\\[[33m\\]"
declare -- LP_COLOR_DISCHARGING_UNDER="\\[[31m\\]"
declare -- LP_COLOR_DISK="\\[[1m[31m\\]"
declare -- LP_COLOR_DISK_UNITS="\\[[31m\\]"
declare -- LP_COLOR_ENV_VARS_SET="\\[[1m[34m\\]"
declare -- LP_COLOR_ENV_VARS_UNSET="\\[[34m\\]"
declare -- LP_COLOR_ERR="\\[[35m\\]"
declare -- LP_COLOR_ERR_MEANING="\\[[35m\\]"
declare -- LP_COLOR_HOST=""
declare -- LP_COLOR_HOST_HASH="\\[[36m\\]"
declare -- LP_COLOR_IN_MULTIPLEXER="\\[[1m[34m\\]"
declare -- LP_COLOR_JOB_D="\\[[33m\\]"
declare -- LP_COLOR_JOB_R="\\[[1m[33m\\]"
declare -- LP_COLOR_JOB_Z="\\[[1m[33m\\]"
declare -- LP_COLOR_KUBECONTEXT="\\[[36m\\]"
declare -- LP_COLOR_MARK="\\[[1m\\]"
declare -- LP_COLOR_MARK_ROOT="\\[[1m[31m\\]"
declare -- LP_COLOR_MARK_SUDO="\\[[1m[31m\\]"
declare -- LP_COLOR_MODULES="\\[[34m\\]"
declare -- LP_COLOR_NODE_VENV="\\[[36m\\]"
declare -- LP_COLOR_NOWRITE="\\[[31m\\]"
declare -- LP_COLOR_PATH="\\[(B[m\\]"
declare -- LP_COLOR_PATH_LAST_DIR="\\[(B[m[1m\\]"
declare -- LP_COLOR_PATH_ROOT="\\[[1m[33m\\]"
declare -- LP_COLOR_PATH_SEPARATOR="\\[(B[m[90m\\]"
declare -- LP_COLOR_PATH_SHORTENED="\\[(B[m[90m\\]"
declare -- LP_COLOR_PATH_VCS_ROOT="\\[(B[m[1m\\]"
declare -- LP_COLOR_PERL_VENV="\\[[36m\\]"
declare -- LP_COLOR_PROXY="\\[[1m[34m\\]"
declare -- LP_COLOR_RAM="\\[[1m[31m\\]"
declare -- LP_COLOR_RAM_UNITS="\\[[31m\\]"
declare -- LP_COLOR_RUBY_VENV="\\[[36m\\]"
declare -- LP_COLOR_RUNTIME="\\[[33m\\]"
declare -- LP_COLOR_SHLVL="\\[[1m[32m\\]"
declare -- LP_COLOR_SSH="\\[[34m\\]"
declare -- LP_COLOR_SU="\\[[1m[33m\\]"
declare -- LP_COLOR_TELNET="\\[[30m[41m\\]"
declare -- LP_COLOR_TERRAFORM="\\[[1m[35m\\]"
declare -- LP_COLOR_TIME="\\[[34m\\]"
declare -- LP_COLOR_UP="\\[[32m\\]"
declare -- LP_COLOR_USER=""
declare -- LP_COLOR_USER_ALT="\\[[1m\\]"
declare -- LP_COLOR_USER_LOGGED=""
declare -- LP_COLOR_USER_ROOT="\\[[1m[33m\\]"
declare -- LP_COLOR_VIRTUALENV="\\[[36m\\]"
declare -- LP_COLOR_WRITE="\\[[32m\\]"
declare -- LP_COLOR_X11_OFF="\\[[33m\\]"
declare -- LP_COLOR_X11_ON="\\[[32m\\]"
declare -- LP_CONTAINER=""
declare -- LP_DEBUG_TIME="0"
declare -- LP_DELIMITER_KUBECONTEXT_PREFIX=""
declare -- LP_DELIMITER_KUBECONTEXT_SUFFIX=""
declare -- LP_DEV_ENV=""
declare -- LP_DIRSTACK=""
declare -a LP_DISABLED_VCS_PATHS=()
declare -- LP_DISK=""
declare -- LP_DISK_PRECISION="2"
declare -- LP_DISK_THRESHOLD="102400"
declare -- LP_DISK_THRESHOLD_PERC="10"
declare -- LP_DISPLAY_VALUES_AS_PERCENTS="0"
declare -- LP_ENABLE_AWS_PROFILE="1"
declare -- LP_ENABLE_BATT="1"
declare -- LP_ENABLE_BZR="0"
declare -- LP_ENABLE_CHROOT="1"
declare -- LP_ENABLE_CMAKE="0"
declare -- LP_ENABLE_COLOR="1"
declare -- LP_ENABLE_CONTAINER="0"
declare -- LP_ENABLE_DETACHED_SESSIONS="1"
declare -- LP_ENABLE_DIRSTACK="0"
declare -- LP_ENABLE_DISK="0"
declare -- LP_ENABLE_DISPLAY="1"
declare -- LP_ENABLE_ENV_VARS="1"
declare -- LP_ENABLE_ERROR="1"
declare -- LP_ENABLE_ERROR_MEANING="0"
declare -- LP_ENABLE_ERROR_MEANING_EXTENDED="0"
declare -- LP_ENABLE_FOSSIL="0"
declare -- LP_ENABLE_GIT="1"
declare -- LP_ENABLE_HG="1"
declare -- LP_ENABLE_HYPERLINKS="0"
declare -- LP_ENABLE_JOBS="1"
declare -- LP_ENABLE_KUBECONTEXT="0"
declare -- LP_ENABLE_KUBE_NAMESPACE="0"
declare -- LP_ENABLE_LOAD="1"
declare -- LP_ENABLE_MODULES="1"
declare -- LP_ENABLE_MODULES_HASHCOLOR="0"
declare -- LP_ENABLE_MODULES_VERSIONS="1"
declare -- LP_ENABLE_MULTIPLEXER="1"
declare -- LP_ENABLE_NODE_VENV="0"
declare -- LP_ENABLE_OS="0"
declare -- LP_ENABLE_OS_ARCH="0"
declare -- LP_ENABLE_OS_DISTRIB="0"
declare -- LP_ENABLE_OS_FAMILY="0"
declare -- LP_ENABLE_OS_KERNEL="1"
declare -- LP_ENABLE_OS_VERSION="1"
declare -- LP_ENABLE_PATH="1"
declare -- LP_ENABLE_PERL_VENV="0"
declare -- LP_ENABLE_PERM="1"
declare -- LP_ENABLE_PROXY="1"
declare -- LP_ENABLE_RAM="1"
declare -- LP_ENABLE_RUBY_VENV="0"
declare -- LP_ENABLE_RUNTIME="1"
declare -- LP_ENABLE_RUNTIME_BELL="0"
declare -- LP_ENABLE_SCLS="1"
declare -- LP_ENABLE_SCREEN_TITLE="0"
declare -- LP_ENABLE_SHLVL="1"
declare -- LP_ENABLE_SHORTEN_PATH="1"
declare -- LP_ENABLE_SSH_COLORS="0"
declare -- LP_ENABLE_SUDO="0"
declare -- LP_ENABLE_SVN="1"
declare -- LP_ENABLE_TEMP="1"
declare -- LP_ENABLE_TERRAFORM="0"
declare -- LP_ENABLE_TIME="0"
declare -- LP_ENABLE_TITLE="0"
declare -- LP_ENABLE_TITLE_COMMAND="0"
declare -- LP_ENABLE_TMUX_TITLE_PANES="1"
declare -- LP_ENABLE_VCS_REMOTE="0"
declare -- LP_ENABLE_VCS_ROOT="0"
declare -- LP_ENABLE_VIRTUALENV="1"
declare -- LP_ENABLE_WIFI_STRENGTH="0"
declare -- LP_ENVVARS=""
declare -a LP_ENV_VARS=()
declare -- LP_ERR=""
declare -- LP_ERR_MEANING=""
declare -- LP_HG_COMMAND="hg"
declare -- LP_HIDE_EMPTY_ERROR="1"
declare -- LP_HOST=""
declare -- LP_HOSTNAME_ALWAYS="0"
declare -- LP_HOSTNAME_METHOD="short"
declare -- LP_JOBS="\\[[33m\\]2d\\[(B[m\\] "
declare -- LP_KUBECONTEXT=""
declare -- LP_LOAD=""
declare -- LP_LOAD_CAP="2.0"
declare -- LP_LOAD_THRESHOLD="0.60"
declare -- LP_MARK="±\\[(B[m\\] "
declare -- LP_MARK_ADAPTER="⏚"
declare -- LP_MARK_BATTERY="⌁"
declare -- LP_MARK_BRACKET_CLOSE="]"
declare -- LP_MARK_BRACKET_OPEN="["
declare -- LP_MARK_BZR="⚯"
declare -- LP_MARK_CMAKE=":"
declare -- LP_MARK_DEFAULT="\$"
declare -- LP_MARK_DEV_CLOSE=">"
declare -- LP_MARK_DEV_MID="|"
declare -- LP_MARK_DEV_OPEN="<"
declare -- LP_MARK_DIRSTACK="⚞"
declare -- LP_MARK_DISABLED="⌀"
declare -- LP_MARK_DISK="🖴 "
declare -- LP_MARK_ENV_VARS_CLOSE=")"
declare -- LP_MARK_ENV_VARS_OPEN="("
declare -- LP_MARK_ENV_VARS_SEP=" "
declare -- LP_MARK_FOSSIL="⌘"
declare -- LP_MARK_GIT="±"
declare -- LP_MARK_HG="☿"
declare -- LP_MARK_JOBS_SEPARATOR="/"
declare -- LP_MARK_KUBECONTEXT="⎈"
declare -- LP_MARK_LOAD="⌂"
declare -- LP_MARK_MODULES_CLOSE=""
declare -- LP_MARK_MODULES_OPEN=""
declare -- LP_MARK_MODULES_SEP=":"
declare -- LP_MARK_MULTIPLEXER_CLOSE="]"
declare -- LP_MARK_MULTIPLEXER_OPEN="["
declare -a LP_MARK_OS=()
declare -- LP_MARK_OS_SEP="/"
declare -- LP_MARK_PERM=":"
declare -- LP_MARK_PREFIX="
declare -- LP_MARK_PROXY="↥"
declare -- LP_MARK_RAM="M"
declare -- LP_MARK_SHLVL="└"
declare -- LP_MARK_SHORTEN_PATH=" … "
declare -- LP_MARK_STASH="+"
declare -- LP_MARK_SVN="‡"
declare -- LP_MARK_TEMP="θ"
declare -- LP_MARK_UNTRACKED="*"
declare -- LP_MARK_VCSH="|"
declare -- LP_MARK_VCS_REMOTE="⭚"
declare -- LP_MARK_WIFI="📶"
declare -- LP_MODULES=""
declare -- LP_NODE_VENV=""
declare -- LP_OLD_PS1="\${debian_chroot:+(\$debian_chroot)}\\u@\\h:\\w\\\$ "
declare -- LP_OLD_PWD="LP:/srv/checkouts/ubuntu/usr/local/src/liquidprompt"
declare -- LP_OPSYS=""
declare -- LP_OS="Linux"
declare -- LP_PATH_CHARACTER_KEEP="3"
declare -- LP_PATH_KEEP="2"
declare -- LP_PATH_LENGTH="35"
declare -- LP_PATH_METHOD="truncate_chars_from_path_left"
declare -- LP_PATH_VCS_ROOT="1"
declare -- LP_PERL_VENV=""
declare -- LP_PERM="\\[[31m\\]:\\[(B[m\\]"
declare -- LP_PROXY=""
declare -- LP_PS1=""
declare -- LP_PS1_POSTFIX=""
declare -- LP_PS1_PREFIX=""
declare -- LP_PWD="\\[(B[m\\]/\\[(B[m\\]srv\\[(B[m[90m\\]/\\[(B[m\\]checkouts\\[(B[m[90m\\]/\\[(B[m\\]ubuntu\\[(B[m[90m\\]/\\[(B[m\\]usr\\[(B[m[90m\\]/\\[(B[m\\]local\\[(B[m[90m\\]/\\[(B[m\\]src\\[(B[m[90m\\]/\\[(B[m[1m\\]liquidprompt\\[(B[m\\]"
declare -- LP_RAM=""
declare -- LP_RAM_PRECISION="2"
declare -- LP_RAM_THRESHOLD="102400"
declare -- LP_RAM_THRESHOLD_PERC="10"
declare -a LP_RUBY_RVM_PROMPT_OPTIONS=([0]="i" [1]="v" [2]="g" [3]="s")
declare -- LP_RUBY_VENV=""
declare -- LP_RUNTIME=""
declare -- LP_RUNTIME_BELL_THRESHOLD="10"
declare -- LP_RUNTIME_THRESHOLD="2"
declare -- LP_SCLS=""
declare -- LP_SHLVL=""
declare -- LP_SHLVL_THRESHOLD="2"
declare -- LP_TEMP=""
declare -a LP_TEMP_SYSFS_IGNORE_FILES=()
declare -- LP_TEMP_THRESHOLD="60"
declare -- LP_TFSPACE=""
declare -- LP_THEME="default"
declare -- LP_TIME=""
declare -- LP_TIME_ANALOG="0"
declare -- LP_TIME_FORMAT="%H:%M:%S"
declare -- LP_TITLE_CLOSE="\\"
declare -- LP_TITLE_OPEN="]2"
declare -- LP_TTYN="16"
declare -- LP_USER=""
declare -- LP_USER_ALWAYS="0"
declare -- LP_VCS=" \\[[32m\\]\\[(B[m\\]"
declare -- LP_VENV=""
declare -- LP_WIFI=""
declare -- LP_WIFI_STRENGTH_THRESHOLD="40"
```

**Comment by steelman** [comment]
@rpatterson
Please, run `./tools/external-tool-tester.sh > broken-error-reporting.txt` in the liquidprompt source directory and upload the `broken-error-reporting.txt` file here. Do not copy-n-paste it, attach to your reply to to _this_ post. TIA.

**Comment by rpatterson** [comment]
I think I found the causal variable in my usage. When I reproduced the issue I was using [ntfy to send push notifications on completion of shell commands regardless of exit status code](https://ntfy.readthedocs.io/en/latest/#shell-integration) and had the following in my `/etc/bash.bashrc`:

```
LP_USER_ALWAYS=0
LP_MARK_PREFIX=$'\n'
[[ $- = *i* ]] && source /srv/checkouts/ubuntu/usr/local/src/liquidprompt/liquidprompt

eval "$(ntfy shell-integration --foreground-too)"
```

With that order I got notifications via ntfy but lost non-zero exit status codes from LiquidPrompt (the `$ sleep 11` is a command that runs long enough to trigger an ntfy notification):

```
⌂11.05 [@library:~]
$ ^C
⌂11.05 [@library:~]
$ false
⌂10.40 [@library:~]
$ ls jhggyyhg
ls: cannot access 'jhggyyhg': No such file or directory
⌂9.97 [@library:~]
$ sleep 11
```

Then I reversed the order like so in `/etc/bash.bashrc`:

```
eval "$(ntfy shell-integration --foreground-too)"

LP_USER_ALWAYS=0
LP_MARK_PREFIX=$'\n'
[[ $- = *i* ]] && source /srv/checkouts/ubuntu/usr/local/src/liquidprompt/liquidprompt
```

With this new order, I got both notifications via ntfy *and* non-zero exit status codes from LiquidPrompt:

```
⌂8.61 [@library:~]
$ ^C
⌂8.61 [@library:~]
$ false
⌂8.96 [@library:~] 1(error)
$ sleep 11
```

So I have a workaround.

I'm a little concerned, however, that it indicates that merging #827 made LiquidPrompt more particular/fragile when interacting with other shell tools than it was before. I would be surprised if ntfy were the *only* shell tool whose users are affected similarly.

> Please, run `./tools/external-tool-tester.sh > broken-error-reporting.txt`

LMK if you'd still like that output. Or if there's any other way I can help for that matter.

P.S. I'd completely forgotten that GitHub grew the ability to handle big attachments more gracefully. Sorry!

**Comment by steelman** [comment]
Could you also post the output of `ntfy shell-integration --foreground-too`, please?

**Comment by Rycieos** [comment]
> Could you also post the output of `ntfy shell-integration --foreground-too`, please?

Looks like ntfy exports first [this file](https://github.com/dschep/ntfy/blob/398014eee761082ec15f8d7ab0433ee73ee7f734/ntfy/shell_integration/bash-preexec.sh) and then [this file](https://github.com/dschep/ntfy/blob/398014eee761082ec15f8d7ab0433ee73ee7f734/ntfy/shell_integration/auto-ntfy-done.sh). So basically it bundles bash-preexec.

I can reproduce this by sourcing bash-preexec after liquidprompt.

Anyway, this is expected, as both bash-preexec and Liquid Prompt do the same checks for determining if the preexec hooks should be ran, and if you install bash-preexec after, it steals away from Liquid Prompt the info it needs to do those checks.

This means there are 2 ways to prevent the issue:
1. Run `eval "$(ntfy shell-integration ...` before `. liquidprompt`. This loads bash-preexec first, and Liquid Prompt will detect it and use it.
2. Run bash-preexec manually first, then liquidprompt, and then `eval "$(ntfy shell-integration ...`.

Anway, this falls under the wiki entry of [Prompt timing and/or error display isn't working](https://github.com/liquidprompt/liquidprompt/wiki/FAQ#prompt-timing-andor-error-display-isnt-working). (To be fair, this entry didn't mention error display until just now, but the rest is the same.)

There is also [an entry in the install documentation](https://liquidprompt.readthedocs.io/en/v2.2.0/install.html#shell-installation) mentioning this exactly, but I'll forgive you for not knowing as you likely did not know that ntfy used bash-preexec. I think I'll improve that callout slightly anyway.

**Comment by rpatterson** [comment]
Thanks for the detailed explanation, again! ;-)

> There is also [an entry in the install documentation](https://liquidprompt.readthedocs.io/en/v2.2.0/install.html#shell-installation) mentioning this exactly, but I'll forgive you for not knowing as you likely did not know that ntfy used bash-preexec. I think I'll improve that callout slightly anyway.

Indeed I did not know that. It looks like [bash-preexec knows some of the other tools using it](https://github.com/rcaloras/bash-preexec?tab=readme-ov-file#bash-preexec):

> This project is currently being used in production by [Bashhub](https://github.com/rcaloras/bashhub-client), [iTerm2](https://github.com/gnachman/iTerm2), and [Fig](https://fig.io/).

So maybe it's worth mentioning those tools and ntfy in the docs? That would make this class of issues more discoverable for others like me who didn't know that warning call out applies to them. I suppose the mentions here in this issue also help make it discoverable.

> Anyway, this is expected, as both bash-preexec and Liquid Prompt do the same checks for determining if the preexec hooks should be ran, and if you install bash-preexec after, it steals away from Liquid Prompt the info it needs to do those checks.

Makes sense, but why did merging PR #827 make this caveat apply to users of bash-preexec when it didn't before. I also confirmed that even *with* ntfy loaded last, I can't reproduce the issue when PR #827 is disabled with `LP_HIDE_EMPTY_ERROR=0`. So it seems like PR #827 introduced something that makes the LiquidPrompt default configuration susceptible to that bash-preexec caveat when it wasn't before.

> This means there are 2 ways to prevent the issue:
> 
> 1. Run `eval "$(ntfy shell-integration ...` before `. liquidprompt`. This loads bash-preexec first, and Liquid Prompt will detect it and use it.

Regardless, I'll happily obey the LiquidPrompt docs now that I understand how it applies to me and load ntfy first. Thanks again for the explanation!

**Comment by Rycieos** [comment]
> Makes sense, but why did merging PR #827 make this caveat apply to users of bash-preexec when it didn't before. I also confirmed that even _with_ ntfy loaded last, I can't reproduce the issue when PR #827 is disabled with `LP_HIDE_EMPTY_ERROR=0`. 

That PR added `LP_HIDE_EMPTY_ERROR` as an option, so without that patch `LP_HIDE_EMPTY_ERROR` won't do anything.

> So it seems like PR #827 introduced something that makes the LiquidPrompt default configuration susceptible to that bash-preexec caveat when it wasn't before.

Correct. Half of the behavior of `LP_HIDE_EMPTY_ERROR=1` is to hide the error display if `<Enter>` was pressed on an empty prompt. The easy way to detect this is by reusing the logic used by both Liquid Prompt and bash-preexec to only run preexec hooks when a command is actually run. But that relies on that logic working, and if bash-preexec breaks Liquid Prompt's logic, Liquid Prompt thinks that every prompt is on an empty line, and so never shows any error code.

You can see that here:
https://github.com/liquidprompt/liquidprompt/pull/827/files#diff-ef34fce883a908e05fe28695e45b06605246681c63a017518178cb02f456af09R4861-R4870
It is done as part of preexec, and will never run if bash-preexec is installed second.

And now I realize there is another option:

3. Init liquidprompt, then nfty, then run `lp_activate`.

This is *not* ideal, as each part of Liquid Prompt would run twice, but Liquid Prompt would detect bash-preexec and inject its hooks correctly. But again, not ideal, don't do that.
