### ISSUE TITLE
Simple VCS blacklist

### ISSUE THREAD

**Issue by mobrembski** [liquidprompt/liquidprompt#844]
I suggest to add maybe a simple config item to blacklist VCS functionality for certain of paths.

There is an high latency issue when you use liquidprompt and enter to some big repo. 
Running any comand results in a few seconds delay in getting back to shell again after finishing execution of previous command.

It happens because repo is big with lot of files, lot of changed files, and liquidprompt does something to obtain information from git repo status. I didn't check what exact commands are executed, but i dont think it matters.

I suggest just to add some config item to specify in bash array style paths which will have VCS features disabled.

**Comment by Rycieos** [comment]
This exists already, see config option [LP_DISABLED_VCS_PATHS](https://liquidprompt.readthedocs.io/en/stable/config.html#LP_DISABLED_VCS_PATHS).
