### ISSUE TITLE
Question: meaning of the electrical grounding mark

### ISSUE THREAD

**Issue by martinschayna** [liquidprompt/liquidprompt#845]
A fresh install of Ubuntu 24.04 with a liquid prompt and minor configuration has been done (less information in the prompt, only git VCS allowed, etc.). There is no `LP_MARK_(whatever)` in the config file. There is a strange mark at the beginning of the prompt; it looks like an electrical grounding/earthing symbol. The terminal uses a Standard Monospace font; as far as I know, there are no ligatures in my terminal.

![image](https://github.com/user-attachments/assets/f2148d7f-6a8b-49dd-b5ec-41af8e72cbc3)

Could you please explain what it means? Thank you.

**Comment by Rycieos** [comment]
This is [`LP_MARK_ADAPTER`](https://liquidprompt.readthedocs.io/en/stable/config.html#LP_MARK_ADAPTER), meaning a battery was detected, but the device is plugged into external power.

[`LP_ENABLE_BATT`](https://liquidprompt.readthedocs.io/en/stable/config.html#LP_ENABLE_BATT) defaults to on, so you must have missed turning it off.

If your device does not have a battery, then this is a bug, and we can dig deeper if you can provide more information.
