### ISSUE TITLE
Show elapsed correctly even if the system clock changed while the command was running

### ISSUE THREAD

**Issue by ardrabczyk** [liquidprompt/liquidprompt#847]
Example:

    [ja:~] $ sudo date --set='1 hour'
    Fri Sep 20 05:43:48 CEST 2024
    [ja:~] 1h0m0s $

I was thinking that maybe liquidprompt could take time from /proc/uptime instead of using $SECONDS variable? For example like that:

```diff
diff --git a/liquidprompt b/liquidprompt
index ea8e998..84af407 100755
--- a/liquidprompt
+++ b/liquidprompt
@@ -4035,14 +4035,14 @@ _lp_runtime_format() {
 }
 
 __lp_runtime_before() {
-    _LP_RUNTIME_LAST_SECONDS=$SECONDS
+    _LP_RUNTIME_LAST_SECONDS="$(awk -F. '{print $1}' /proc/uptime)"
     _LP_RUNTIME_SECONDS=-1
 }
 
 # Compute number of seconds since the command was started
 __lp_runtime_after() {
     if [[ -n "${_LP_RUNTIME_LAST_SECONDS-}" ]]; then
-        (( _LP_RUNTIME_SECONDS=SECONDS-_LP_RUNTIME_LAST_SECONDS ))
+        (( _LP_RUNTIME_SECONDS="$(awk -F. '{print $1}' /proc/uptime)"-_LP_RUNTIME_LAST_SECONDS ))
         unset _LP_RUNTIME_LAST_SECONDS
     else
         _LP_RUNTIME_SECONDS=0
@@ -5175,7 +5175,6 @@ prompt_on() {
 
             if (( ${_LP_ENABLE_PREEXEC-0} )); then
                 _LP_AT_PROMPT=0
-                _LP_RUNTIME_LAST_SECONDS=$SECONDS
                 # __lp_before_command gets called just before bash executes a command,
                 # including $PROMPT_COMMAND
                 # Pass $_ to this call, because it sets $_ to what it already was

```

It's just an improvement, not a bug.

**Comment by Rycieos** [comment]
You are correct, it would be an improvement, not a bug fix. I do not think that this is a bug. And honestly, it is debatable if this is even an improvement as there could be valid reasons for the clock drifting that would give a more accurate runtime. And how often are you changing your clock, anyway?

Regardless, going from a zero impact read of `$SECONDS` to one or two forking calls is too high a price to pay for this improvement. And we can't read `/proc/uptime` on non-Linux systems, so we would need to call `uptime`, `sysctl`, or similar, and those tools don't show enough detail for seconds resolution.

So this patch is un-mergable as it is, and I do not think a portable version would be worth it either.
