### ISSUE TITLE
__lp_disable_hooks does not remove __lp_before_command from DEBUG trap

### ISSUE THREAD

**Issue by softmoth** [liquidprompt/liquidprompt#849]
The `__lp_before_command` function continues to run due to the `DEBUG` trap after the prompt is extinguished with `prompt_OFF`. It should not be.

This becomes an issue mainly when `PROMPT_COMMAND` is empty, because `__lp_before_command` unconditionally examines the last element, which causes bash to cry foul (`bad array subscript`).

### NOTE: Known issue

This is a known issue, see the comment in [`__lp_disable_hooks`](https://github.com/liquidprompt/liquidprompt/blob/b6909c6e1808fa04a89cf00ab57adb9ff1041b19/liquidprompt#L5282-L5286) for details.

Bug report file: 
[bug-report.txt](https://github.com/user-attachments/files/17343725/bug-report.txt)

### Steps to Reproduce

1) Start with a clean bash environment, without _liquidprompt_ loaded. Ensure that `PROMPT_COMMAND` is empty.
2) Note that bash does not print any `bad array subscript` warnings about the empty `PROMPT_COMMAND` array.
3) source `liquidprompt`
4) Note that everything is working normally
5) Restore the environment with `prompt_OFF`, which calls `__lp_disable_hooks`
6) Note that bash starts to complain.

Example:

```
$ for x in "${PROMPT_COMMAND[@]}"; do echo "'$x'"; done
$ trap -p DEBUG
$ source ~/g/liquidprompt/liquidprompt
θ72° [trs:~]└3 $ for x in "${PROMPT_COMMAND[@]}"; do echo "'$x'"; done
'__lp_set_prompt'
θ73° [trs:~]└3 $ trap -p DEBUG
trap -- '__lp_before_command "$_"' DEBUG
θ74° [trs:~]└3 $ prompt_OFF
$ for x in "${PROMPT_COMMAND[@]}"; do echo "'$x'"; done
$ trap -p DEBUG
bash: PROMPT_COMMAND: bad array subscript
trap -- '__lp_before_command "$_"' DEBUG
$ echo hi
bash: PROMPT_COMMAND: bad array subscript
hi
$ trap - DEBUG
bash: PROMPT_COMMAND: bad array subscript
$ echo hi
hi
$ 
```

### Expected Behavior

After `prompt_OFF`, no liquidprompt functions should be called automatically.

### Current Behavior

See above.

### Possible Solution

Add this to `__lp_disable_hooks`
```
trap -p DEBUG | grep __lp_before_command >/dev/null && trap - DEBUG
```

**Comment by Rycieos** [comment]
Thanks for the report. The reproduction steps are clear.

Unfortunately, your suggested solution doesn't work. It already exists, actually:
https://github.com/liquidprompt/liquidprompt/blob/b6909c6e1808fa04a89cf00ab57adb9ff1041b19/liquidprompt#L5282-L5286

The problem is that setting (or unsetting) a trap will set the function scoped trap if run inside a function. The Bash manual claims:

       declare [-aAfFgiIlnrtux] [-p] [name[=value] ...]
       typeset [-aAfFgiIlnrtux] [-p] [name[=value] ...]
              ...
              -f     Use function names only.
              ...
              -t     Give each name the trace attribute.  Traced functions inherit the DEBUG and RETURN traps from the calling shell.  The trace attribute has no special meaning for variables.

Which seems that if you add `declare -f -t __lp_disable_hooks`, that function would work with the shell traps. But my testing shows that does not work, even on modern versions on Bash (5.2):

```
$ source ~/dev/liquidprompt/liquidprompt
[mark:~/Users/mark] $ declare -fp __lp_disable_hooks
__lp_disable_hooks ()
{
    ...
}
declare -ft __lp_disable_hooks
[mark:~/Users/mark] $ prompt_OFF
$ trap -p DEBUG
bash: PROMPT_COMMAND: bad array subscript
trap -- '__lp_before_command "$_"' DEBUG
```

However, if you call the function directly, then it does:

```
$ __lp_disable_hooks
bash: PROMPT_COMMAND: bad array subscript
$ trap -p DEBUG
$
```
My guess is that `declare -t` makes the function inherit the traps of the parent context, not the shell. And since the parent function is either `prompt_off()` or `prompt_OFF()`, this doesn't work.

But, it does work recursively, so we can just set all the functions that could reasonably call `__lp_disable_hooks()`.

Could you try this patch? It works for all my testing.

```diff
diff --git a/liquidprompt b/liquidprompt
index bdec7c5..aaa136d 100755
--- a/liquidprompt
+++ b/liquidprompt
@@ -5088,7 +5088,9 @@ __lp_before_command() {
     # time, so no elif is used.
     local first_command last_command
     first_command=$PROMPT_COMMAND
-    if (( ${BASH_VERSINFO[0]:-0} > 5 || ( ${BASH_VERSINFO[0]:-0} == 5 && ${BASH_VERSINFO[1]:-0} >= 1 ) )); then
+    if (( ( ${BASH_VERSINFO[0]:-0} > 5 \
+        || ( ${BASH_VERSINFO[0]:-0} == 5 && ${BASH_VERSINFO[1]:-0} >= 1 )) \
+        && ${#PROMPT_COMMAND[@]} > 1 )); then
         last_command=${PROMPT_COMMAND[-1]}
     else
         last_command=$PROMPT_COMMAND
@@ -5280,7 +5282,6 @@ __lp_disable_hooks() {
             fi

             # Disable the DEBUG trap used by the RUNTIME or TITLE_COMMAND features
-            # TODO: Fix this: Bash will unset the function's DEBUG trap, not the global one.
             if (( ${_LP_ENABLE_PREEXEC-0} )); then
                 trap - DEBUG
             fi
@@ -5326,6 +5327,11 @@ prompt_OFF() {
     PS1="$_LP_MARK_SYMBOL "
 }

+if (( _LP_SHELL_bash )); then
+    # These functions must inherit shell traps to be able to disable them.
+    declare -f -t __lp_disable_hooks lp_activate prompt_off prompt_OFF
+fi
+
 lp_theme() {
     local theme="${1-}"
```

**Comment by softmoth** [comment]
Thanks, Mark. It works for me. After `prompt_OFF` the trap is reset.
