### ISSUE TITLE
Incorrect uncommitted line count for bzr, fossil, and svn

### ISSUE THREAD

**Issue by faelys** [liquidprompt/liquidprompt#850]
Bug report file: [bug-report.txt](https://github.com/user-attachments/files/17682963/bug-report.txt)

### Steps to Reproduce

1. Use liquidprompt with a prompt showing the number of uncommitted lines
2. Move to a directory with a file tracked in a bzr, fossil, or svn repository
3. Add lines terminated by `-` or remove lines terminated by `+`
4. Compare the number of uncommitted lines reported in the prompt to the actual number of committed lines

### Expected Behavior

The numbers should be equal

### Current Behavior

The numbers are not equal : the added lines ending with `-` are also counted as removals, and the removed lines ending with `+` are also counted as additions.

If lines ending with `-` or `+` appear in the context lines, they are also (mis)counted.

### Possible Solution

For these three VCS, the number of uncommitted lines is counted using the following awk script:
```
BEGIN { plus=0; minus=0 }
/^(\+[^+])|(\+$)/ { plus+=1 }
/^(-[^-])|(-$)/ { minus+=1 }
END { print plus" "minus }
```
I'm not really sure what is the rationale or intent behind these regexes, I guess when adding or removing an empty lines, the trailing space after `+` or `-` might be missing. However it seems both BSD awk and GNU awk have the `|` at higher priority than the `^`, so the right part matches any line ending with `+` or `-`.

I think I would go for `/(^\+[^+])|(^\+$)/` and `/(^-[^-])|(^-$)/` despite the parentheses being redundant, and there might even more clever, shorter, and harder to read alternatives.

**Comment by Rycieos** [comment]
Thanks for the report! That's a tricky one. Thanks for tracking it down and finding a solution. I have taken your suggestion verbatim, so I gave you authorship credit.
